### PR TITLE
Polygon support

### PR DESCRIPTION
**Pull request by bakingam1983**
I've added PolygonScan support

### CODE REVIEW

**Comment by hoss-green** [comment]
I've seen this, I'm going to rewrite a little, I feel like having more than one bool can get confusing, so I'd rather switch to an enum. Will try and get this done this week.

**Comment by ihorbond** [comment]
Hey @hoss-green do you think it'd be easier/more flexible to just allow the user to pass in the network's api url along with the api key ? cause I would also need avax and ftm

**Comment by bakingam1983** [comment]
Yes, it is probably the best solution.
Even if the API endpoints change in future

**Comment by ihorbond** [comment]
hey @hoss-green can you please provide feedback ?

**Comment by hoss-green** [comment]
Hey @ihorbond, 

My apologies for the slow responses, I am recovering from covid. 

Yes, I agree, adding the ability to support urls would be a good thing, it would also allow for network changes without too much fuss.

**Comment by hoss-green** [comment]
Closed, as it's been added in the latest push

**Pull request closed without merging**
